# Generated by Django 5.1.2 on 2026-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default_image.webp",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
