# Generated by Django 6.0.3 on 2026-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default_image.webp", null=True, upload_to="images/"
            ),
        ),
    ]
