# Generated by Django 6.0.3 on 2026-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
